const mongoose = require('mongoose');

const SimulationSchema = new mongoose.Schema({
  promptId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Prompt',
    required: true
  },
  // The details generated by AI, specific to the type of simulation
  generatedEmail: { // Only populated if the prompt was for an email
    subject: { type: String },
    sender: { type: String },
    recipient: { type: String },
    body: { type: String },
    links: [{
      text: { type: String },
      url: { type: String },
      isPhishing: { type: Boolean }
    }],
    attachments: [{ type: String }]
  },
  generatedSms: { // NEW: Only populated if the prompt was for an SMS
    senderPhone: { type: String },
    recipientPhone: { type: String },
    message: { type: String },
    links: [{
      text: { type: String },
      url: { type: String },
      isPhishing: { type: Boolean }
    }]
  },
  // You can add fields for user interaction later, e.g.:
  // interaction: {
  //     clickedLink: { type: Boolean, default: false },
  //     submittedData: { type: Boolean, default: false },
  //     detectedAsPhishing: { type: Boolean, default: false },
  //     interactionTimestamp: { type: Date }
  // },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Simulation', SimulationSchema);